# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches:
      - main
      - '*.x'
    tags:
      - '*'
  pull_request:
    branches:
  schedule:
    # Weekly Monday 9AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 9 * * 1'

env:
  CRDS_SERVER_URL: "https://roman-crds-dev.stsci.edu"
  CRDS_PATH: "/tmp/crds_cache"
  CRDS_CLIENT_RETRY_COUNT: 3
  CRDS_CLIENT_RETRY_DELAY_SECONDS: 20

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Code style checks
            os: ubuntu-latest
            python: 3.x
            toxenv: codestyle

          - name: Python 3.8
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-test

          - name: Python 3.9
            os: ubuntu-latest
            python: 3.9
            toxenv: py39-test

          - name: Python 3.8 with dev dependencies
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-test-devdeps

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: Run tests
      run: tox -e ${{ matrix.toxenv }}
